name: Build and Publish Nuget Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build TypeChatSharp/TypeChatSharp.csproj --configuration Release

    - name: Pack Nuget package
      run: dotnet pack TypeChatSharp/TypeChatSharp.csproj --configuration Release

    - name: Push Nuget package to nuget.org
      run: dotnet nuget push TypeChatSharp/bin/Release/TypeChatSharp.*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate 
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}